package com.magento.idea.magento2plugin.mcp;

import com.magento.idea.magento2plugin.mcp.util.PropertyParsingUtil;
import org.junit.Test;
import org.junit.Assert;

import java.util.List;
import java.util.Map;

/**
 * Test case for PropertyParsingUtil functionality used by EntityCreationHandler.
 */
public class EntityCreationHandlerTest {

    @Test
    public void testParseFormattedPropertiesString() {
        // Test with properties from the issue example
        // Create the formatted string that would be generated by ClassPropertyFormatterUtil
        String testFormattedString = "ENTITY_ID;entity_id;int;EntityId;entityId,NUMBER_OF_CALLS;number_of_calls;string;NumberOfCalls;numberOfCalls,ROUTE;route;string;Route;route";

        // Call the static utility method
        List<Map<String, String>> result = PropertyParsingUtil.parseFormattedPropertiesString(testFormattedString);

        // Verify the results
        Assert.assertNotNull("Result should not be null", result);
        Assert.assertEquals("Should have 3 properties", 3, result.size());

        // Check first property (entity_id)
        Map<String, String> firstProperty = result.get(0);
        Assert.assertEquals("First property name should be entity_id", "entity_id", firstProperty.get("Name"));
        Assert.assertEquals("First property type should be int", "int", firstProperty.get("Type"));

        // Check second property (number_of_calls)
        Map<String, String> secondProperty = result.get(1);
        Assert.assertEquals("Second property name should be number_of_calls", "number_of_calls", secondProperty.get("Name"));
        Assert.assertEquals("Second property type should be string", "string", secondProperty.get("Type"));

        // Check third property (route)
        Map<String, String> thirdProperty = result.get(2);
        Assert.assertEquals("Third property name should be route", "route", thirdProperty.get("Name"));
        Assert.assertEquals("Third property type should be string", "string", thirdProperty.get("Type"));
    }

    @Test
    public void testParseFormattedPropertiesStringEmpty() {
        // Test with empty string
        List<Map<String, String>> result = PropertyParsingUtil.parseFormattedPropertiesString("");

        // Verify the results
        Assert.assertNotNull("Result should not be null", result);
        Assert.assertEquals("Should have 0 properties for empty string", 0, result.size());

        // Test with null string
        List<Map<String, String>> nullResult = PropertyParsingUtil.parseFormattedPropertiesString(null);

        // Verify the results
        Assert.assertNotNull("Result should not be null for null input", nullResult);
        Assert.assertEquals("Should have 0 properties for null input", 0, nullResult.size());
    }

    @Test
    public void testParseFormattedPropertiesStringWithWhitespace() {
        // Test with whitespace and malformed entries
        String testFormattedString = " ENTITY_ID;entity_id;int;EntityId;entityId , , NUMBER_OF_CALLS;number_of_calls;string;NumberOfCalls;numberOfCalls ";

        List<Map<String, String>> result = PropertyParsingUtil.parseFormattedPropertiesString(testFormattedString);

        // Verify the results
        Assert.assertNotNull("Result should not be null", result);
        Assert.assertEquals("Should have 2 properties (ignoring empty entries)", 2, result.size());

        // Check first property (entity_id)
        Map<String, String> firstProperty = result.get(0);
        Assert.assertEquals("First property name should be entity_id", "entity_id", firstProperty.get("Name"));
        Assert.assertEquals("First property type should be int", "int", firstProperty.get("Type"));

        // Check second property (number_of_calls)
        Map<String, String> secondProperty = result.get(1);
        Assert.assertEquals("Second property name should be number_of_calls", "number_of_calls", secondProperty.get("Name"));
        Assert.assertEquals("Second property type should be string", "string", secondProperty.get("Type"));
    }
}